/**
 * System Status Enums and Payment Methods
 */
const ATTENDANCE_STATUS = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  LATE: 'LATE',
  HALF_DAY: 'HALF_DAY',
  EXCUSED: 'EXCUSED'
};

const FEE_STATUS = {
  PENDING: 'PENDING',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  PAID: 'PAID',
  OVERDUE: 'OVERDUE'
};

const PAYMENT_METHOD = {
  CASH: 'CASH',
  UPI: 'UPI',
  CARD: 'CARD',
  BANK_TRANSFER: 'BANK_TRANSFER',
  ONLINE: 'ONLINE',
  CHEQUE: 'CHEQUE',
  OTHER: 'OTHER'
};

const CASH_SESSION_STATUS = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
  RECONCILED: 'RECONCILED'
};

const LEAVE_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED'
};

const LEAVE_TYPE = {
  CASUAL: 'CASUAL',
  SICK: 'SICK',
  MATERNITY: 'MATERNITY',
  PATERNITY: 'PATERNITY',
  UNPAID: 'UNPAID'
};

const EXAM_STATUS = {
  SCHEDULED: 'SCHEDULED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  PUBLISHED: 'PUBLISHED'
};

const HOMEWORK_STATUS = {
  ASSIGNED: 'ASSIGNED',
  SUBMITTED: 'SUBMITTED',
  LATE: 'LATE',
  REVIEWED: 'REVIEWED'
};

const BOOK_STATUS = {
  AVAILABLE: 'AVAILABLE',
  ISSUED: 'ISSUED',
  LOST: 'LOST',
  DAMAGED: 'DAMAGED'
};

const INVENTORY_MOVEMENT_TYPE = {
  STOCK_IN: 'STOCK_IN',
  STOCK_OUT: 'STOCK_OUT',
  ADJUSTMENT: 'ADJUSTMENT',
  RETURN: 'RETURN',
  SCRAP: 'SCRAP'
};

const AUDIT_ACTION = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
  PAYMENT: 'PAYMENT',
  REFUND: 'REFUND',
  FEE_CHANGE: 'FEE_CHANGE',
  RESULT_PUBLISH: 'RESULT_PUBLISH',
  RESULT_UPDATE: 'RESULT_UPDATE',
  USER_ROLE_CHANGE: 'USER_ROLE_CHANGE',
  SETTINGS_CHANGE: 'SETTINGS_CHANGE'
};

module.exports = {
  ATTENDANCE_STATUS,
  FEE_STATUS,
  PAYMENT_METHOD,
  CASH_SESSION_STATUS,
  LEAVE_STATUS,
  LEAVE_TYPE,
  EXAM_STATUS,
  HOMEWORK_STATUS,
  BOOK_STATUS,
  INVENTORY_MOVEMENT_TYPE,
  AUDIT_ACTION
};
